baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Nicholas Montana's Blog"
theme = "shibui"

[params]
    author = "Nicholas Montana"
    email = "nmontana745@gmail.com"

[menu]
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 2